// image data
#define TEXSIZ_GACHA_W 128
#define TEXSIZ_GACHA_H 128
#define TEXSIZ_GACHA_WH 128, 128
#define TEXPOS_GACHA_PROMOTION_X 0
#define TEXPOS_GACHA_PROMOTION_Y 0
#define TEXPOS_GACHA_PROMOTION_W 100
#define TEXPOS_GACHA_PROMOTION_H 100
#define TEXPOS_GACHA_PROMOTION_XYWH 0, 0, 100, 100
