// image data
#define TEXSIZ_MEISTER_W 512
#define TEXSIZ_MEISTER_H 512
#define TEXSIZ_MEISTER_WH 512, 512
#define TEXPOS_MEISTER_WORKSPACE_X 0
#define TEXPOS_MEISTER_WORKSPACE_Y 0
#define TEXPOS_MEISTER_WORKSPACE_W 128
#define TEXPOS_MEISTER_WORKSPACE_H 184
#define TEXPOS_MEISTER_WORKSPACE_XYWH 0, 0, 128, 184
#define TEXPOS_MEISTER_PROFILE_X 130
#define TEXPOS_MEISTER_PROFILE_Y 0
#define TEXPOS_MEISTER_PROFILE_W 280
#define TEXPOS_MEISTER_PROFILE_H 360
#define TEXPOS_MEISTER_PROFILE_XYWH 130, 0, 280, 360
