// image data
#define TEXSIZ_PUPPET_W 512
#define TEXSIZ_PUPPET_H 512
#define TEXSIZ_PUPPET_WH 512, 512
#define TEXPOS_PUPPET_DOT_X 0
#define TEXPOS_PUPPET_DOT_Y 0
#define TEXPOS_PUPPET_DOT_W 256
#define TEXPOS_PUPPET_DOT_H 256
#define TEXPOS_PUPPET_DOT_XYWH 0, 0, 256, 256
#define TEXPOS_PUPPET_PROFILE_X 258
#define TEXPOS_PUPPET_PROFILE_Y 0
#define TEXPOS_PUPPET_PROFILE_W 240
#define TEXPOS_PUPPET_PROFILE_H 320
#define TEXPOS_PUPPET_PROFILE_XYWH 258, 0, 240, 320
#define TEXPOS_PUPPET_SHADOW_X 0
#define TEXPOS_PUPPET_SHADOW_Y 256
#define TEXPOS_PUPPET_SHADOW_W 32
#define TEXPOS_PUPPET_SHADOW_H 32
#define TEXPOS_PUPPET_SHADOW_XYWH 0, 256, 32, 32
