// image data
#define TEXSIZ_SYSTEM_W 1024
#define TEXSIZ_SYSTEM_H 1024
#define TEXSIZ_SYSTEM_WH 1024, 1024
#define TEXPOS_SYSTEM_IMAGETITLE_X 86
#define TEXPOS_SYSTEM_IMAGETITLE_Y 0
#define TEXPOS_SYSTEM_IMAGETITLE_W 240
#define TEXPOS_SYSTEM_IMAGETITLE_H 200
#define TEXPOS_SYSTEM_IMAGETITLE_XYWH 86, 0, 240, 200
#define TEXPOS_SYSTEM_BOXWHITE_X 0
#define TEXPOS_SYSTEM_BOXWHITE_Y 0
#define TEXPOS_SYSTEM_BOXWHITE_W 32
#define TEXPOS_SYSTEM_BOXWHITE_H 32
#define TEXPOS_SYSTEM_BOXWHITE_XYWH 0, 0, 32, 32
#define TEXPOS_SYSTEM_BOXBASIC_X 0
#define TEXPOS_SYSTEM_BOXBASIC_Y 34
#define TEXPOS_SYSTEM_BOXBASIC_W 41
#define TEXPOS_SYSTEM_BOXBASIC_H 41
#define TEXPOS_SYSTEM_BOXBASIC_XYWH 0, 34, 41, 41
#define TEXPOS_SYSTEM_BUTTONBASICNORMAL_X 43
#define TEXPOS_SYSTEM_BUTTONBASICNORMAL_Y 0
#define TEXPOS_SYSTEM_BUTTONBASICNORMAL_W 41
#define TEXPOS_SYSTEM_BUTTONBASICNORMAL_H 49
#define TEXPOS_SYSTEM_BUTTONBASICNORMAL_XYWH 43, 0, 41, 49
#define TEXPOS_SYSTEM_BUTTONBASICACTIVE_X 43
#define TEXPOS_SYSTEM_BUTTONBASICACTIVE_Y 51
#define TEXPOS_SYSTEM_BUTTONBASICACTIVE_W 41
#define TEXPOS_SYSTEM_BUTTONBASICACTIVE_H 49
#define TEXPOS_SYSTEM_BUTTONBASICACTIVE_XYWH 43, 51, 41, 49
#define TEXPOS_SYSTEM_BUTTONBASICSELECT_X 43
#define TEXPOS_SYSTEM_BUTTONBASICSELECT_Y 102
#define TEXPOS_SYSTEM_BUTTONBASICSELECT_W 41
#define TEXPOS_SYSTEM_BUTTONBASICSELECT_H 49
#define TEXPOS_SYSTEM_BUTTONBASICSELECT_XYWH 43, 102, 41, 49
#define TEXPOS_SYSTEM_BUTTONBASICINACTIVE_X 43
#define TEXPOS_SYSTEM_BUTTONBASICINACTIVE_Y 153
#define TEXPOS_SYSTEM_BUTTONBASICINACTIVE_W 41
#define TEXPOS_SYSTEM_BUTTONBASICINACTIVE_H 49
#define TEXPOS_SYSTEM_BUTTONBASICINACTIVE_XYWH 43, 153, 41, 49
#define TEXPOS_SYSTEM_BUTTONCTRLBTNNORMAL_X 0
#define TEXPOS_SYSTEM_BUTTONCTRLBTNNORMAL_Y 77
#define TEXPOS_SYSTEM_BUTTONCTRLBTNNORMAL_W 41
#define TEXPOS_SYSTEM_BUTTONCTRLBTNNORMAL_H 49
#define TEXPOS_SYSTEM_BUTTONCTRLBTNNORMAL_XYWH 0, 77, 41, 49
#define TEXPOS_SYSTEM_BUTTONCTRLBTNACTIVE_X 0
#define TEXPOS_SYSTEM_BUTTONCTRLBTNACTIVE_Y 128
#define TEXPOS_SYSTEM_BUTTONCTRLBTNACTIVE_W 41
#define TEXPOS_SYSTEM_BUTTONCTRLBTNACTIVE_H 49
#define TEXPOS_SYSTEM_BUTTONCTRLBTNACTIVE_XYWH 0, 128, 41, 49
#define TEXPOS_SYSTEM_BUTTONPICKERNORMAL_X 86
#define TEXPOS_SYSTEM_BUTTONPICKERNORMAL_Y 202
#define TEXPOS_SYSTEM_BUTTONPICKERNORMAL_W 56
#define TEXPOS_SYSTEM_BUTTONPICKERNORMAL_H 60
#define TEXPOS_SYSTEM_BUTTONPICKERNORMAL_XYWH 86, 202, 56, 60
#define TEXPOS_SYSTEM_BUTTONPICKERACTIVE_X 144
#define TEXPOS_SYSTEM_BUTTONPICKERACTIVE_Y 202
#define TEXPOS_SYSTEM_BUTTONPICKERACTIVE_W 56
#define TEXPOS_SYSTEM_BUTTONPICKERACTIVE_H 60
#define TEXPOS_SYSTEM_BUTTONPICKERACTIVE_XYWH 144, 202, 56, 60
#define TEXPOS_SYSTEM_BUTTONPICKERSELECT_X 202
#define TEXPOS_SYSTEM_BUTTONPICKERSELECT_Y 202
#define TEXPOS_SYSTEM_BUTTONPICKERSELECT_W 56
#define TEXPOS_SYSTEM_BUTTONPICKERSELECT_H 60
#define TEXPOS_SYSTEM_BUTTONPICKERSELECT_XYWH 202, 202, 56, 60
#define TEXPOS_SYSTEM_BUTTONPICKERINACTIVE_X 260
#define TEXPOS_SYSTEM_BUTTONPICKERINACTIVE_Y 202
#define TEXPOS_SYSTEM_BUTTONPICKERINACTIVE_W 56
#define TEXPOS_SYSTEM_BUTTONPICKERINACTIVE_H 60
#define TEXPOS_SYSTEM_BUTTONPICKERINACTIVE_XYWH 260, 202, 56, 60
#define TEXPOS_SYSTEM_BUTTONCTRLUPNORMAL_X 0
#define TEXPOS_SYSTEM_BUTTONCTRLUPNORMAL_Y 264
#define TEXPOS_SYSTEM_BUTTONCTRLUPNORMAL_W 68
#define TEXPOS_SYSTEM_BUTTONCTRLUPNORMAL_H 96
#define TEXPOS_SYSTEM_BUTTONCTRLUPNORMAL_XYWH 0, 264, 68, 96
#define TEXPOS_SYSTEM_BUTTONCTRLDNNORMAL_X 94
#define TEXPOS_SYSTEM_BUTTONCTRLDNNORMAL_Y 338
#define TEXPOS_SYSTEM_BUTTONCTRLDNNORMAL_W 68
#define TEXPOS_SYSTEM_BUTTONCTRLDNNORMAL_H 96
#define TEXPOS_SYSTEM_BUTTONCTRLDNNORMAL_XYWH 94, 338, 68, 96
#define TEXPOS_SYSTEM_BUTTONCTRLRTNORMAL_X 70
#define TEXPOS_SYSTEM_BUTTONCTRLRTNORMAL_Y 264
#define TEXPOS_SYSTEM_BUTTONCTRLRTNORMAL_W 92
#define TEXPOS_SYSTEM_BUTTONCTRLRTNORMAL_H 72
#define TEXPOS_SYSTEM_BUTTONCTRLRTNORMAL_XYWH 70, 264, 92, 72
#define TEXPOS_SYSTEM_BUTTONCTRLLTNORMAL_X 0
#define TEXPOS_SYSTEM_BUTTONCTRLLTNORMAL_Y 362
#define TEXPOS_SYSTEM_BUTTONCTRLLTNORMAL_W 92
#define TEXPOS_SYSTEM_BUTTONCTRLLTNORMAL_H 72
#define TEXPOS_SYSTEM_BUTTONCTRLLTNORMAL_XYWH 0, 362, 92, 72
#define TEXPOS_SYSTEM_BUTTONCTRLUPACTIVE_X 164
#define TEXPOS_SYSTEM_BUTTONCTRLUPACTIVE_Y 264
#define TEXPOS_SYSTEM_BUTTONCTRLUPACTIVE_W 68
#define TEXPOS_SYSTEM_BUTTONCTRLUPACTIVE_H 96
#define TEXPOS_SYSTEM_BUTTONCTRLUPACTIVE_XYWH 164, 264, 68, 96
#define TEXPOS_SYSTEM_BUTTONCTRLDNACTIVE_X 258
#define TEXPOS_SYSTEM_BUTTONCTRLDNACTIVE_Y 338
#define TEXPOS_SYSTEM_BUTTONCTRLDNACTIVE_W 68
#define TEXPOS_SYSTEM_BUTTONCTRLDNACTIVE_H 96
#define TEXPOS_SYSTEM_BUTTONCTRLDNACTIVE_XYWH 258, 338, 68, 96
#define TEXPOS_SYSTEM_BUTTONCTRLRTACTIVE_X 234
#define TEXPOS_SYSTEM_BUTTONCTRLRTACTIVE_Y 264
#define TEXPOS_SYSTEM_BUTTONCTRLRTACTIVE_W 92
#define TEXPOS_SYSTEM_BUTTONCTRLRTACTIVE_H 72
#define TEXPOS_SYSTEM_BUTTONCTRLRTACTIVE_XYWH 234, 264, 92, 72
#define TEXPOS_SYSTEM_BUTTONCTRLLTACTIVE_X 164
#define TEXPOS_SYSTEM_BUTTONCTRLLTACTIVE_Y 362
#define TEXPOS_SYSTEM_BUTTONCTRLLTACTIVE_W 92
#define TEXPOS_SYSTEM_BUTTONCTRLLTACTIVE_H 72
#define TEXPOS_SYSTEM_BUTTONCTRLLTACTIVE_XYWH 164, 362, 92, 72
#define TEXPOS_SYSTEM_FONTABCD_X 0
#define TEXPOS_SYSTEM_FONTABCD_Y 436
#define TEXPOS_SYSTEM_FONTABCD_W 320
#define TEXPOS_SYSTEM_FONTABCD_H 180
#define TEXPOS_SYSTEM_FONTABCD_XYWH 0, 436, 320, 180
#define TEXPOS_SYSTEM_FONTHIRA_X 0
#define TEXPOS_SYSTEM_FONTHIRA_Y 616
#define TEXPOS_SYSTEM_FONTHIRA_W 320
#define TEXPOS_SYSTEM_FONTHIRA_H 180
#define TEXPOS_SYSTEM_FONTHIRA_XYWH 0, 616, 320, 180
#define TEXPOS_SYSTEM_FONTKATA_X 0
#define TEXPOS_SYSTEM_FONTKATA_Y 796
#define TEXPOS_SYSTEM_FONTKATA_W 320
#define TEXPOS_SYSTEM_FONTKATA_H 180
#define TEXPOS_SYSTEM_FONTKATA_XYWH 0, 796, 320, 180
#define TEXPOS_SYSTEM_FONTNUMBER_X 0
#define TEXPOS_SYSTEM_FONTNUMBER_Y 976
#define TEXPOS_SYSTEM_FONTNUMBER_W 200
#define TEXPOS_SYSTEM_FONTNUMBER_H 30
#define TEXPOS_SYSTEM_FONTNUMBER_XYWH 0, 976, 200, 30
#define TEXPOS_SYSTEM_FONTKANJI_X 200
#define TEXPOS_SYSTEM_FONTKANJI_Y 976
#define TEXPOS_SYSTEM_FONTKANJI_W 80
#define TEXPOS_SYSTEM_FONTKANJI_H 30
#define TEXPOS_SYSTEM_FONTKANJI_XYWH 200, 976, 80, 30
#define TEXPOS_SYSTEM_IMAGEPLAYERICON_X 874
#define TEXPOS_SYSTEM_IMAGEPLAYERICON_Y 0
#define TEXPOS_SYSTEM_IMAGEPLAYERICON_W 88
#define TEXPOS_SYSTEM_IMAGEPLAYERICON_H 88
#define TEXPOS_SYSTEM_IMAGEPLAYERICON_XYWH 874, 0, 88, 88
#define TEXPOS_SYSTEM_IMAGEPUPPETCAGE_X 874
#define TEXPOS_SYSTEM_IMAGEPUPPETCAGE_Y 180
#define TEXPOS_SYSTEM_IMAGEPUPPETCAGE_W 120
#define TEXPOS_SYSTEM_IMAGEPUPPETCAGE_H 120
#define TEXPOS_SYSTEM_IMAGEPUPPETCAGE_XYWH 874, 180, 120, 120
#define TEXPOS_SYSTEM_IMAGEMAPCHIP_X 328
#define TEXPOS_SYSTEM_IMAGEMAPCHIP_Y 302
#define TEXPOS_SYSTEM_IMAGEMAPCHIP_W 256
#define TEXPOS_SYSTEM_IMAGEMAPCHIP_H 256
#define TEXPOS_SYSTEM_IMAGEMAPCHIP_XYWH 328, 302, 256, 256
#define TEXPOS_SYSTEM_IMAGEMONEY_X 586
#define TEXPOS_SYSTEM_IMAGEMONEY_Y 302
#define TEXPOS_SYSTEM_IMAGEMONEY_W 60
#define TEXPOS_SYSTEM_IMAGEMONEY_H 60
#define TEXPOS_SYSTEM_IMAGEMONEY_XYWH 586, 302, 60, 60
#define TEXPOS_SYSTEM_IMAGEITEM_X 648
#define TEXPOS_SYSTEM_IMAGEITEM_Y 302
#define TEXPOS_SYSTEM_IMAGEITEM_W 60
#define TEXPOS_SYSTEM_IMAGEITEM_H 60
#define TEXPOS_SYSTEM_IMAGEITEM_XYWH 648, 302, 60, 60
#define TEXPOS_SYSTEM_IMAGECARD_X 586
#define TEXPOS_SYSTEM_IMAGECARD_Y 364
#define TEXPOS_SYSTEM_IMAGECARD_W 128
#define TEXPOS_SYSTEM_IMAGECARD_H 184
#define TEXPOS_SYSTEM_IMAGECARD_XYWH 586, 364, 128, 184
#define TEXPOS_SYSTEM_IMAGESLIDE_X 716
#define TEXPOS_SYSTEM_IMAGESLIDE_Y 364
#define TEXPOS_SYSTEM_IMAGESLIDE_W 270
#define TEXPOS_SYSTEM_IMAGESLIDE_H 180
#define TEXPOS_SYSTEM_IMAGESLIDE_XYWH 716, 364, 270, 180
#define TEXPOS_SYSTEM_IMAGERESULT_X 322
#define TEXPOS_SYSTEM_IMAGERESULT_Y 560
#define TEXPOS_SYSTEM_IMAGERESULT_W 240
#define TEXPOS_SYSTEM_IMAGERESULT_H 240
#define TEXPOS_SYSTEM_IMAGERESULT_XYWH 322, 560, 240, 240
#define TEXPOS_SYSTEM_IMAGETUTORIALNAVI_X 806
#define TEXPOS_SYSTEM_IMAGETUTORIALNAVI_Y 560
#define TEXPOS_SYSTEM_IMAGETUTORIALNAVI_W 120
#define TEXPOS_SYSTEM_IMAGETUTORIALNAVI_H 160
#define TEXPOS_SYSTEM_IMAGETUTORIALNAVI_XYWH 806, 560, 120, 160
#define TEXPOS_SYSTEM_IMAGETUTORIALARROW_X 806
#define TEXPOS_SYSTEM_IMAGETUTORIALARROW_Y 722
#define TEXPOS_SYSTEM_IMAGETUTORIALARROW_W 80
#define TEXPOS_SYSTEM_IMAGETUTORIALARROW_H 80
#define TEXPOS_SYSTEM_IMAGETUTORIALARROW_XYWH 806, 722, 80, 80
#define TEXPOS_SYSTEM_IMAGETUTORIALPOINT_X 806
#define TEXPOS_SYSTEM_IMAGETUTORIALPOINT_Y 804
#define TEXPOS_SYSTEM_IMAGETUTORIALPOINT_W 80
#define TEXPOS_SYSTEM_IMAGETUTORIALPOINT_H 80
#define TEXPOS_SYSTEM_IMAGETUTORIALPOINT_XYWH 806, 804, 80, 80
